### ISSUE TITLE
Unfriendly error message when Git credentials are missing

### ISSUE THREAD

**Issue by jwadolowski** [Knotx/knotx-cookbook#4]
By accident I forgot to pass `default['knotx']['config']['git_user']` and `default['knotx']['config']['git_pass']` attributes and ended up with `Installing knotx instance 'publish' failed!` message, which is not really accurate, as majority of the deployment has been completed successfully. It'd be great to display a bit more verbose message to end user

```
==> default: [2017-07-27T17:48:17+02:00] INFO: directory[/opt/knotx/publish/config] created directory /opt/knotx/publish/config
==> default:
==> default:       - create new directory /opt/knotx/publish/config
==> default: [2017-07-27T17:48:17+02:00] INFO: directory[/opt/knotx/publish/config] owner changed to 994
==> default: [2017-07-27T17:48:17+02:00] INFO: directory[/opt/knotx/publish/config] group changed to 991
==> default: [2017-07-27T17:48:17+02:00] INFO: directory[/opt/knotx/publish/config] mode changed to 755
==> default:
==> default:       - change mode from '' to '0755'
==> default:       - change owner from '' to 'knotx'
==> default:
==> default:       - change group from '' to 'knotx'
==> default:
==> default: [2017-07-27T17:48:17+02:00] FATAL: Installing knotx instance 'publish' failed!
==> default:
==> default:     ================================================================================
==> default:     Error executing action `install` on resource 'knotx_instance[knot.x publish]'
==> default:     ================================================================================
==> default:
==> default:     SystemExit
==> default:     ----------
==> default:     exit
==> default:
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/knotx/libraries/provider_knotx_instance.rb:252:in `rescue in action_install'
==> default:     /var/chef/cache/cookbooks/knotx/libraries/provider_knotx_instance.rb:220:in `action_install'
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/hmicom-knotx/recipes/publish.rb
==> default:
==> default:      18: knotx_instance "knot.x #{local_id}" do
==> default:      19:   id local_id
==> default:      20:   version node['hmicom-knotx']['version']
==> default:      21: end
==> default:      22:
```

**Comment by karoldrazek** [comment]
Good point. Will increase verbosity.
